definitions:
  model.Product:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock_quantity:
        type: integer
      theme:
        type: string
    type: object
  request.WarehouseStatus:
    properties:
      id:
        type: integer
      is_active:
        type: boolean
    type: object
  request.WarehouseTransferRequest:
    properties:
      from_warehouse_id:
        type: integer
      product_id:
        type: integer
      quantity:
        type: integer
      to_warehouse_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /warehouse/status:
    post:
      description: Update status warehouse
      parameters:
      - description: body
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.WarehouseStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: Update status warehouse
  /warehouse/transfer:
    post:
      description: Transfer Stock of product between warehouse
      parameters:
      - description: body
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.WarehouseTransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: Transfer Stock of product between warehouse
swagger: "2.0"
